### ISSUE TITLE
Include COPYING in git-version-macro crate

### ISSUE THREAD

**Issue by ignatenkobrain** [fusion-engineering/rust-git-version#14]
Hello,

Crate archive on crates.io (https://crates.io/api/v1/crates/git-version-macro/0.3.4/download#/git-version-macro-0.3.4.crate) does not contain COPYING file which would be super helpful when packaging that crate for Fedora (and other Linux distributions).

Please add it.

Thanks!

**Comment by de-vri-es** [comment]
With version 0.3.5 the file is now included in the macro crate too.

Just curious: how exactly does packaging rust crates work? Wouldn't cargo always download the dependencies from crates.io anyway?

**Comment by decathorpe** [comment]
> With version 0.3.5 the file is now included in the macro crate too.

Thanks! Sorry for the late reply. Looks like Igor is busy doing other things, but I can give you a quick response here.

> Just curious: how exactly does packaging rust crates work? Wouldn't cargo always download the dependencies from crates.io anyway?

Not really. The way it works in Fedora: We basically package the published crate sources from crates.io (so one crate maps to one source package), and in our case, we have some automated tools that map dependency and feature information from `Cargo.toml` to native RPM metadata and subpackages 1:1.

A Rust package build then involves the following steps:

- map `Cargo.toml` dependencies to identifiers that the native package manager can resolve to "native" RPM packages that contain those crates' sources
- install those Rust crate packages into the build environment
- configure cargo to use a shared directory containing the necessary crate sources as a local registry, instead of connecting to the internet / crates.io
- run "cargo build" to check if things build
- install crate sources to "local registry"
- run "cargo install" if we're building a binary
- run "cargo test" to make sure we didn't mess anything up
- generate native package manager metadata from `Cargo.toml` (preserving features, optional dependencies, etc.)

Doing it this way (and because we can map cargo metadata to and from RPM package metadata without losing any information), we don't need to reinvent the wheel, but can instead leverage features that are officially supported by the Rust toolchain / cargo. As far as I know, the OpenSUSE and Mageia Rust packaging tools are based on the ones from Fedora, so those work the same way. I do not know about debian-based distros, but I think they work in a similar way, too.

Hope this explanation makes sense.

**Comment by de-vri-es** [comment]
Thanks for the explanation, always interesting to learn such things :)
